#ifndef DATA_SHP1_H_
#define DATA_SHP1_H_

#include "life/fsm.h"

#define DATA_SHP1_AS_STAND              FSM_STATE_STAND
#define DATA_SHP1_AS_TURN_CW_S          (FSM_STATE_CUSTOM_START + 0)
#define DATA_SHP1_AS_TURN_CW_F          (FSM_STATE_CUSTOM_START + 1)
#define DATA_SHP1_AS_TURN_CC_S          (FSM_STATE_CUSTOM_START + 2)
#define DATA_SHP1_AS_TURN_CC_F          (FSM_STATE_CUSTOM_START + 3)
#define DATA_SHP1_AS_MOVE_U_S           (FSM_STATE_CUSTOM_START + 4)
#define DATA_SHP1_AS_MOVE_U_F           (FSM_STATE_CUSTOM_START + 5)
#define DATA_SHP1_AS_MOVE_UR_S          (FSM_STATE_CUSTOM_START + 6)
#define DATA_SHP1_AS_MOVE_UR_F          (FSM_STATE_CUSTOM_START + 7)
#define DATA_SHP1_AS_MOVE_R_S           (FSM_STATE_CUSTOM_START + 8)
#define DATA_SHP1_AS_MOVE_R_F           (FSM_STATE_CUSTOM_START + 9)
#define DATA_SHP1_AS_MOVE_DR_S          (FSM_STATE_CUSTOM_START + 10)
#define DATA_SHP1_AS_MOVE_DR_F          (FSM_STATE_CUSTOM_START + 11)
#define DATA_SHP1_AS_MOVE_D_S           (FSM_STATE_CUSTOM_START + 12)
#define DATA_SHP1_AS_MOVE_D_F           (FSM_STATE_CUSTOM_START + 13)
#define DATA_SHP1_AS_MOVE_DL_S          (FSM_STATE_CUSTOM_START + 14)
#define DATA_SHP1_AS_MOVE_DL_F          (FSM_STATE_CUSTOM_START + 15)
#define DATA_SHP1_AS_MOVE_L_S           (FSM_STATE_CUSTOM_START + 16)
#define DATA_SHP1_AS_MOVE_L_F           (FSM_STATE_CUSTOM_START + 17)
#define DATA_SHP1_AS_MOVE_UL_S          (FSM_STATE_CUSTOM_START + 18)
#define DATA_SHP1_AS_MOVE_UL_F          (FSM_STATE_CUSTOM_START + 19)
#define DATA_SHP1_AS_MOVE_U_TURN_CW_S   (FSM_STATE_CUSTOM_START + 20)
#define DATA_SHP1_AS_MOVE_U_TURN_CW_F   (FSM_STATE_CUSTOM_START + 21)
#define DATA_SHP1_AS_MOVE_U_TURN_CC_S   (FSM_STATE_CUSTOM_START + 22)
#define DATA_SHP1_AS_MOVE_U_TURN_CC_F   (FSM_STATE_CUSTOM_START + 23)
#define DATA_SHP1_AS_MOVE_D_TURN_CW_S   (FSM_STATE_CUSTOM_START + 24)
#define DATA_SHP1_AS_MOVE_D_TURN_CW_F   (FSM_STATE_CUSTOM_START + 25)
#define DATA_SHP1_AS_MOVE_D_TURN_CC_S   (FSM_STATE_CUSTOM_START + 26)
#define DATA_SHP1_AS_MOVE_D_TURN_CC_F   (FSM_STATE_CUSTOM_START + 27)
#define DATA_SHP1_AS_MOVE_C_U_S         (FSM_STATE_CUSTOM_START + 28)
#define DATA_SHP1_AS_MOVE_C_U_F         (FSM_STATE_CUSTOM_START + 29)
#define DATA_SHP1_AS_MOVE_C_UR_S        (FSM_STATE_CUSTOM_START + 30)
#define DATA_SHP1_AS_MOVE_C_UR_F        (FSM_STATE_CUSTOM_START + 31)
#define DATA_SHP1_AS_MOVE_C_R_S         (FSM_STATE_CUSTOM_START + 32)
#define DATA_SHP1_AS_MOVE_C_R_F         (FSM_STATE_CUSTOM_START + 33)
#define DATA_SHP1_AS_MOVE_C_DR_S        (FSM_STATE_CUSTOM_START + 34)
#define DATA_SHP1_AS_MOVE_C_DR_F        (FSM_STATE_CUSTOM_START + 35)
#define DATA_SHP1_AS_MOVE_C_D_S         (FSM_STATE_CUSTOM_START + 36)
#define DATA_SHP1_AS_MOVE_C_D_F         (FSM_STATE_CUSTOM_START + 37)
#define DATA_SHP1_AS_MOVE_C_DL_S        (FSM_STATE_CUSTOM_START + 38)
#define DATA_SHP1_AS_MOVE_C_DL_F        (FSM_STATE_CUSTOM_START + 39)
#define DATA_SHP1_AS_MOVE_C_L_S         (FSM_STATE_CUSTOM_START + 40)
#define DATA_SHP1_AS_MOVE_C_L_F         (FSM_STATE_CUSTOM_START + 41)
#define DATA_SHP1_AS_MOVE_C_UL_S        (FSM_STATE_CUSTOM_START + 42)
#define DATA_SHP1_AS_MOVE_C_UL_F        (FSM_STATE_CUSTOM_START + 43)
#define DATA_SHP1_AS_TURN_P_CW_S        (FSM_STATE_CUSTOM_START + 44)
#define DATA_SHP1_AS_TURN_P_CW_F        (FSM_STATE_CUSTOM_START + 45)
#define DATA_SHP1_AS_TURN_P_CC_S        (FSM_STATE_CUSTOM_START + 46)
#define DATA_SHP1_AS_TURN_P_CC_F        (FSM_STATE_CUSTOM_START + 47)
#define DATA_SHP1_AS_BOUNCE_H           (FSM_STATE_CUSTOM_START + 48)
#define DATA_SHP1_AS_BOUNCE_V           (FSM_STATE_CUSTOM_START + 49)
#define DATA_SHP1_AS_SHOOT              (FSM_STATE_CUSTOM_START + 50)
#define DATA_SHP1_AS_SHOOT_REL          (FSM_STATE_CUSTOM_START + 51)
#define DATA_SHP1_AS_USE                (FSM_STATE_CUSTOM_START + 52)
#define DATA_SHP1_AS_REEL               (FSM_STATE_CUSTOM_START + 53)
#define DATA_SHP1_AS_DEAD_IDLE          (FSM_STATE_CUSTOM_START + 54)
#define DATA_SHP1_AS_DEAD_REEL          (FSM_STATE_CUSTOM_START + 55)
#define DATA_SHP1_AS_ANNIHILATE         (FSM_STATE_CUSTOM_START + 56)
#define DATA_SHP1_AS_MAX                (FSM_STATE_CUSTOM_START + 57)

#define DATA_SHP1_AF_STAND              0
#define DATA_SHP1_AF_TURN_CW_S          1
#define DATA_SHP1_AF_TURN_CW_F          2
#define DATA_SHP1_AF_TURN_CC_S          3
#define DATA_SHP1_AF_TURN_CC_F          4
#define DATA_SHP1_AF_MOVE_U_S           5
#define DATA_SHP1_AF_MOVE_U_F           6
#define DATA_SHP1_AF_MOVE_UR_S          7
#define DATA_SHP1_AF_MOVE_UR_F          8
#define DATA_SHP1_AF_MOVE_R_S           9
#define DATA_SHP1_AF_MOVE_R_F           10
#define DATA_SHP1_AF_MOVE_DR_S          11
#define DATA_SHP1_AF_MOVE_DR_F          12
#define DATA_SHP1_AF_MOVE_D_S           13
#define DATA_SHP1_AF_MOVE_D_F           14
#define DATA_SHP1_AF_MOVE_DL_S          15
#define DATA_SHP1_AF_MOVE_DL_F          16
#define DATA_SHP1_AF_MOVE_L_S           17
#define DATA_SHP1_AF_MOVE_L_F           18
#define DATA_SHP1_AF_MOVE_UL_S          19
#define DATA_SHP1_AF_MOVE_UL_F          20
#define DATA_SHP1_AF_MOVE_U_TURN_CW_S   21
#define DATA_SHP1_AF_MOVE_U_TURN_CW_F   22
#define DATA_SHP1_AF_MOVE_U_TURN_CC_S   23
#define DATA_SHP1_AF_MOVE_U_TURN_CC_F   24
#define DATA_SHP1_AF_MOVE_D_TURN_CW_S   25
#define DATA_SHP1_AF_MOVE_D_TURN_CW_F   26
#define DATA_SHP1_AF_MOVE_D_TURN_CC_S   27
#define DATA_SHP1_AF_MOVE_D_TURN_CC_F   28
#define DATA_SHP1_AF_MOVE_C_U_S         29
#define DATA_SHP1_AF_MOVE_C_U_F         30
#define DATA_SHP1_AF_MOVE_C_UR_S        31
#define DATA_SHP1_AF_MOVE_C_UR_F        32
#define DATA_SHP1_AF_MOVE_C_R_S         33
#define DATA_SHP1_AF_MOVE_C_R_F         34
#define DATA_SHP1_AF_MOVE_C_DR_S        35
#define DATA_SHP1_AF_MOVE_C_DR_F        36
#define DATA_SHP1_AF_MOVE_C_D_S         37
#define DATA_SHP1_AF_MOVE_C_D_F         38
#define DATA_SHP1_AF_MOVE_C_DL_S        39
#define DATA_SHP1_AF_MOVE_C_DL_F        40
#define DATA_SHP1_AF_MOVE_C_L_S         41
#define DATA_SHP1_AF_MOVE_C_L_F         42
#define DATA_SHP1_AF_MOVE_C_UL_S        43
#define DATA_SHP1_AF_MOVE_C_UL_F        44
#define DATA_SHP1_AF_BOUNCE_H           45
#define DATA_SHP1_AF_BOUNCE_V           46
#define DATA_SHP1_AF_TURN_P_CW_S        47
#define DATA_SHP1_AF_TURN_P_CW_F        48
#define DATA_SHP1_AF_TURN_P_CC_S        49
#define DATA_SHP1_AF_TURN_P_CC_F        50
#define DATA_SHP1_AF_SHOOT              51
#define DATA_SHP1_AF_SHOOT_REL          52
#define DATA_SHP1_AF_USE                53
#define DATA_SHP1_AF_REEL               54
#define DATA_SHP1_AF_DEAD_IDLE          55
#define DATA_SHP1_AF_DEAD_REEL          56
#define DATA_SHP1_AF_ANNIHILATE         57
#define DATA_SHP1_AF_MAX                58

#endif
