##### Paths
#
# Inputs-
#     o BASE_DIR

##### Paths.
DEMO_DIR := $(BASE_DIR)/demo
TOOL_DIR := $(BASE_DIR)/tools
BIN_DIR := $(BASE_DIR)/bin

LIB_GEN_NAME        := gen
LIB_GEN_DIR         := $(BASE_DIR)/$(LIB_GEN_NAME)
LIB_GEN_BIN_DIR     := $(BIN_DIR)/$(LIB_GEN_NAME)
LIB_GEN_BIN         := $(LIB_GEN_BIN_DIR)/lib$(LIB_GEN_NAME).a

LIB_GFX_NAME     	:= gfx
LIB_GFX_DIR      	:= $(BASE_DIR)/$(LIB_GFX_NAME)
LIB_GFX_BIN_DIR     := $(BIN_DIR)/$(LIB_GFX_NAME)
LIB_GFX_BIN      	:= $(LIB_GFX_BIN_DIR)/lib$(LIB_GFX_NAME).a

LIB_LIFE_NAME     	:= life
LIB_LIFE_DIR      	:= $(BASE_DIR)/$(LIB_LIFE_NAME)
LIB_LIFE_BIN_DIR    := $(BIN_DIR)/$(LIB_LIFE_NAME)
LIB_LIFE_BIN      	:= $(LIB_LIFE_BIN_DIR)/lib$(LIB_LIFE_NAME).a

TOOL_CONST_NAMES_NAME   := const_names.rb
TOOL_CONST_NAMES_DIR    := $(TOOL_DIR)
TOOL_CONST_NAMES_BIN    := $(TOOL_CONST_NAMES_DIR)/$(TOOL_CONST_NAMES_NAME)

TOOL_IMGED_NAME  	:= imged
TOOL_IMGED_DIR   	:= $(TOOL_DIR)/$(TOOL_IMGED_NAME)
TOOL_IMGED_BIN_DIR  := $(BIN_DIR)/$(TOOL_IMGED_NAME)
TOOL_IMGED_BIN   	:= $(TOOL_IMGED_BIN_DIR)/$(TOOL_IMGED_NAME)

DEMO_DEMO01_NAME   	:= demo01
DEMO_DEMO01_DIR    	:= $(DEMO_DIR)/$(DEMO_DEMO01_NAME)
DEMO_DEMO01_BIN_DIR := $(BIN_DIR)/$(DEMO_DEMO01_NAME)
DEMO_DEMO01_BIN    	:= $(DEMO_DEMO01_BIN_DIR)/$(DEMO_DEMO01_NAME)

MK_DIR              := $(BASE_DIR)/mk

##### Misc.
.DEFAULT_GOAL := all

LEAF_SRCS :=
LEAF_OBJS :=
FULL_SRCS :=
FULL_OBJS :=
DEPS :=
OBJS :=
